version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres_2"
    environment:
      - POSTGRES_USER=louise
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=louise
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: